name: Ping Vercel Endpoints

on:
  schedule:
    - cron: '*/10 * * * *'   # news every 10 minutes
    - cron: '*/2 * * * *'    # activity every 2 minutes
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call news endpoint
        if: ${{ secrets.NEWS_URL != '' }}
        run: |
          curl -fsS --max-time 20 "$NEWS_URL" || true
        env:
          NEWS_URL: ${{ secrets.NEWS_URL }}
      - name: Call activity endpoint
        if: ${{ secrets.ACTIVITY_URL != '' }}
        run: |
          curl -fsS --max-time 20 "$ACTIVITY_URL" || true
        env:
          ACTIVITY_URL: ${{ secrets.ACTIVITY_URL }}

